### ISSUE TITLE
Error on CiviCRM 5.44

### ISSUE THREAD

**Issue by allinappli** [Project60/org.project60.sepapp#11]
Using version 1.1dev that comes with the SEPA extension 1.6alpha2 shows this error:

`Deprecated: Array and string offset access syntax with curly braces is deprecated in /home/allingro/testwpcivi/wp-content/uploads/civicrm/ext/org.project60.sepapp-master/sepapp.civix.php on line 260`

It also showed up with version 1.5 of the SEPA extension and version 1.0 of the companion extension

**Comment by bjendres** [comment]
I think there's something with your versioning. [Line 260 of ``sepapp.civix.php``](https://github.com/Project60/org.project60.sepapp/blob/8ec829939220ccf477e24a3f7416193941537448/sepapp.php#L260) is currently:
```
// FIXME: we might consider saving this as a JSON object
```
Maybe try updating the ``org.project60.sepapp`` code to the latest version.

**Comment by allinappli** [comment]
thank you, indeed the file was outdated. Now I have the right file but the site is broken. I'll let you know.

**Comment by allinappli** [comment]
I don't the error any more with this version.

**Comment by bjendres** [comment]
great
