### ISSUE TITLE
PHP 8 compatibility

### ISSUE THREAD

**Issue by eptbertram** [Project60/org.project60.sepapp#14]
I tested sepaPP today with PHP 8.1.11 and could not activate this extension on my CiviCRM 5.53.0 with WordPress 6.0.3. 
Can anybody confirm this? CiviSEPA itself seems to work fine: https://github.com/Project60/org.project60.sepa/issues/645

**Comment by eptbertram** [comment]
> Thanks @eptbertram, would you be able to provide a PR?

I'm sorry, I'm not able to help. Maybe in two weeks.

**Comment by bjendres** [comment]
Sure, whenever you can find the time :) Thanks.

**Comment by tpokorra** [comment]
I think this has already been resolved in master in September 2021 by https://github.com/Project60/org.project60.sepapp/commit/29db6d56800ec996531f84dbb60a1127333892d0
But release 1.0 was before that, in March 2021.

I was able to install sepapp from master with PHP 8.1

**Comment by bjendres** [comment]
@eptbertram, @sebbrandt87: Could you please confirm that [1.1-alpha1](https://github.com/Project60/org.project60.sepapp/releases/tag/1.1-alpha1) works for you (on PHP8)? If so, I'll release it as ``1.1,0``.

**Comment by eptbertram** [comment]
@bjendres @sebbrandt87: Thank you! 
I can confirm that https://github.com/Project60/org.project60.sepapp/releases/tag/1.1-alpha1 is working fine on PHP8.1 (CiviCRM 5.57.0). Go!
