### ISSUE TITLE
PHP 8+ improvements and civix update

### ISSUE THREAD

**Issue by jofranz** [Project60/org.project60.sepapp#32]

**Comment by jofranz** [comment]
We pushed some general fixes and PHP 8+ improvements to `master`.

`master` branch contains all previous fixes (including changes from @bjendres  earlier today).

@bastienho Would be great if you could test it. I would tag a new beta version after hearing from you

**Comment by bastienho** [comment]
Yeah it's good to me.

**Comment by jofranz** [comment]
I tagged a version `1.2-beta3` which reflects the version you tested.
Thanks @bastienho !
